#ifndef FEANORFS_H
#define FEANORFS_H

/* Generated by cbindgen — do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize the shared Tokio runtime. Call once before any other `ffs_*` function.
 * Returns `0` on success, `-1` on error (see `ffs_last_error`).
 */
int32_t ffs_runtime_init(void);

/**
 * Free a string previously returned by any `ffs_*` function (including `ffs_last_error`).
 */
void ffs_string_free(char *s);

/**
 * Last error on **this thread** from the most recent failing `ffs_*` call.
 * Caller must free with `ffs_string_free`. Never NULL (empty string if no error).
 */
char *ffs_last_error(void);

/**
 * List agent workspace names. JSON: `AgentListOfflineResult`. NULL on error.
 */
char *ffs_agent_list(const char *root);

/**
 * Spawn an isolated agent workspace. JSON: `SpawnResult`. NULL on error.
 */
char *ffs_agent_spawn(const char *root, const char *name, int32_t no_sync, int32_t replace);

/**
 * Preview one agent's changes. JSON: `AgentCheckResult`. NULL on error.
 */
char *ffs_agent_status(const char *root, const char *name);

/**
 * Pull cloud changes into the agent. JSON: `AgentRefreshResult`. NULL on error.
 */
char *ffs_agent_refresh(const char *root, const char *name);

/**
 * Integrate agent work into the main workspace. JSON: `AgentLandResult`. NULL on error.
 */
char *ffs_agent_land(const char *root, const char *name, int32_t clean, int32_t propose);

/**
 * Remove an agent workspace. JSON: `AgentCleanResult`. NULL on error.
 */
char *ffs_agent_clean(const char *root, const char *name);

/**
 * Resolve a pending conflict. Returns `0` on success, `-1` on error.
 * `keep`: 0=local, 1=cloud, 2=both, 3=file (requires non-null `file_path`).
 */
int32_t ffs_conflicts_keep(const char *root, const char *path, int32_t keep, const char *file_path);

#endif  /* FEANORFS_H */
